version: '3'

services:
  rethinkdb:
    image: rethinkdb:latest
    ports:
      - "8080:8080" # RethinkDB web UI
      - "28015:28015" # RethinkDB client driver port
      - "29015:29015" # RethinkDB cluster port
    volumes:
      - ./rethinkdb_data:/data # Volume for data persistence
    command: ["rethinkdb", "--bind", "all"]
